version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev # Use the dev Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend-network
    volumes:
      - .:/app # Bind mount to sync code changes
      - /app/node_modules # Exclude node_modules from the bind mount

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Root password
      MYSQL_DATABASE: ${DB_NAME} # Database name
      MYSQL_USER: ${DB_USER} # Non-root username (user)
      MYSQL_PASSWORD: ${DB_PASSWORD} # Password for non-root user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-network

networks:
  backend-network:


volumes:
  db_data:
